### ISSUE TITLE
When no username and apikey are passed, the CLI fails with an unhandled exception.

### ISSUE THREAD

**Issue by stevefox** [nimbix/jarvice_cli#1]
When no username and apikey are passed, the CLI fails with an unhandled exception.

See the following output of `jarvice_cli status` (no ~/.jarvice.cfg and no username/apikey arguments passed in as command-line arguments):

```
[nimbix@JARVICENAE-0A0A184C ~]$ jarvice_cli status
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
/usr/bin/jarvice_cli status
[CRITICAL] jarvice_cli.jarvice_cli.main 367 /usr/bin/jarvice_cli status
/usr/bin/jarvice_cli:369: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  "to support@nimbix.net if it persists." % e.message,
An unknown error as occurred 'module' object has no attribute 'write'. Please report this to support@nimbix.net if it persists.
Traceback (most recent call last):
  File "/usr/bin/jarvice_cli", line 365, in main
    cli_jarvice(known, unknown, parser)
  File "/usr/bin/jarvice_cli", line 320, in cli_jarvice
    _set_credentials(args)
  File "/usr/bin/jarvice_cli", line 225, in _set_credentials
    sys.write.stderr("username and apikey must be passed as arguments "
AttributeError: 'module' object has no attribute 'write'
[CRITICAL] jarvice_cli.jarvice_cli.main 370 An unknown error as occurred 'module' object has no attribute 'write'. Please report this to support@nimbix.net if it persists.
Traceback (most recent call last):
  File "/usr/bin/jarvice_cli", line 365, in main
    cli_jarvice(known, unknown, parser)
  File "/usr/bin/jarvice_cli", line 320, in cli_jarvice
    _set_credentials(args)
  File "/usr/bin/jarvice_cli", line 225, in _set_credentials
    sys.write.stderr("username and apikey must be passed as arguments "
AttributeError: 'module' object has no attribute 'write'
```

**Comment by johnathanhegge** [comment]
was fixed after this apparently:

```
$ jarvice_cli status
username and apikey must be passed as arguments or set in ~/.jarvice.cfg
```
